
[tool.ruff]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    
]

line-length = 100

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402","F401"]
"models.py" = ["E501"]

#Avoid F401 given the way the fixtures work
"test/services/order" = ["F401"]
"test/services/report" = ["F401"]




