name: Python CI

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.x

      - name: Upgrade setuptools
        run: pip install --upgrade setuptools

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Change working directory
        run: cd ${{ github.workspace }}

      - name: Run tests and generate report
        run: |
          pytest --junitxml=report.xml
          echo "::set-output name=report_path::$(pwd)/report.xml"

      - name: Parse test results
        id: parse_results
        run: |
          python .github/workflows/utils/parse_results.py ${{ steps.test.outputs.report_path }}
          echo "::set-output name=passed_tests::${{ steps.parse_results.outputs.passed_tests }}"
          echo "::set-output name=failed_tests::${{ steps.parse_results.outputs.failed_tests }}"
          echo "::set-output name=skipped_tests::${{ steps.parse_results.outputs.skipped_tests }}"

      - name: Generate chart
        id: generate_chart
        run: |
          python .github/workflows/utils/generate_chart.py ${{ steps.parse_results.outputs.passed_tests }} ${{ steps.parse_results.outputs.failed_tests }} ${{ steps.parse_results.outputs.skipped_tests }}
          echo "::set-output name=chart_path::chart.png"

      - name: Create comment with test results
        uses: actions/github-script@v4
        with:
          script: |
            const passed = '${{ steps.parse_results.outputs.passed_tests }}';
            const failed = '${{ steps.parse_results.outputs.failed_tests }}';
            const skipped = '${{ steps.parse_results.outputs.skipped_tests }}';

            const comment = `
            **Test Results**
            - Passed: ${passed}
            - Failed: ${failed}
            - Skipped: ${skipped}
            `;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment.trim()
            })

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: |
            ${{ steps.test.outputs.report_path }}
            ${{ steps.generate_chart.outputs.chart_path }}
