name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update pip
        run: python -m pip install --upgrade pip


      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install --no-binary :all: --no-deps greenlet


      - name: Run tests
        run: python3 manage.py test
