name: Pull Request Commentator

on:
  workflow_call:
    inputs:
      message:
        description: "GitHub bot message"
        required: true
        type: string
      line_to_compare:
        description: "Line to compare"
        required: true
        type: string

jobs:
  commentator:
    runs-on: ubuntu-latest
    steps:
      - name: Comment coverage
        uses: actions/github-script@v6
        with:
          script: |
            const new_comment = `${{ inputs.message }}`;
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              per_page: 100
            });
            const comment = comments.find(comment => {
              return (
                comment.user.login === github.context.actor && comment.body.includes("${{ inputs.line_to_compare }}")
              );
            });
            if (comment) {
              await github.rest.issues.updateComment({
                comment_id: comment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: new_comment,
                token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
              });
            } else {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: new_comment,
                token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
              });
            }
